(define (problem shoe_lacing) (:domain shoe) 
(:objects
	eyelet0 eyelet2 eyelet4 - eyelet_left
	eyelet1 eyelet3 eyelet5 - eyelet_right
)
(:init
	(aglet_at aglet_a site_l1)
	(aglet_at aglet_b site_r1)
	(occupied site_l1)
	(occupied site_r1)
	(at_correct_side aglet_a)
	(at_correct_side aglet_b)
	(left_correct_side aglet_a)
	(right_correct_side aglet_b)
	(lace_with eyelet0 aglet_a)
	(lace_with eyelet3 aglet_a)
	(lace_with eyelet4 aglet_a)
	(lace_with eyelet1 aglet_b)
	(lace_with eyelet2 aglet_b)
	(lace_with eyelet5 aglet_b)
	(block eyelet5 eyelet0)
	(block eyelet5 eyelet1)
	(block eyelet5 eyelet2)
	(block eyelet5 eyelet3)
	(block eyelet4 eyelet0)
	(block eyelet4 eyelet1)
	(block eyelet4 eyelet2)
	(block eyelet4 eyelet3)
	(block eyelet3 eyelet0)
	(block eyelet3 eyelet1)
	(block eyelet2 eyelet0)
	(block eyelet2 eyelet1)
	(block eyelet1 eyelet0)
	(block eyelet3 eyelet2)
	(block eyelet5 eyelet4)
)
(:goal (and
	(eyelet_laced eyelet0)
	(eyelet_laced eyelet1)
	(eyelet_laced eyelet2)
	(eyelet_laced eyelet3)
	(eyelet_laced eyelet4)
	(eyelet_laced eyelet5)
))
)